--
-- PostgreSQL database dump
--

\restrict OgBsXYB4JDo0CXLyVmgLz9WV2uIIqYmaurKAwzb6BkmmxOWa0bWzWtZdhCdyGnR

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carrier_account_ref; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carrier_account_ref (
    id bigint NOT NULL,
    account_name character varying(100),
    account_number character varying(100) NOT NULL,
    active boolean,
    carrier_code character varying(50) NOT NULL,
    client_id character varying(255),
    client_secret character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    customer_no character varying(50),
    environment character varying(20),
    is_default boolean,
    updated_at timestamp(6) without time zone NOT NULL,
    last_verified_at timestamp(6) without time zone,
    verified boolean,
    client_default boolean
);


--
-- Name: carrier_account_ref_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carrier_account_ref ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrier_account_ref_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrier_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carrier_config (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    carrier_code character varying(50) NOT NULL,
    client_id character varying(255),
    client_secret character varying(255),
    account_number character varying(100),
    access_token text,
    token_expiry timestamp without time zone,
    environment character varying(20) DEFAULT 'SANDBOX'::character varying,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    carrier_name character varying(100) NOT NULL,
    token_expires_at timestamp(6) without time zone,
    ship_via_id integer NOT NULL,
    tenant_id character varying(50),
    account_code character varying(50),
    is_default boolean DEFAULT false
);


--
-- Name: carrier_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.carrier_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: carrier_config_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.carrier_config_id_seq OWNED BY public.carrier_config.id;


--
-- Name: client_customs_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client_customs_profile (
    id bigint NOT NULL,
    account_carrier character varying(20),
    account_no character varying(60),
    broker_address1 character varying(255),
    broker_address2 character varying(255),
    broker_city character varying(120),
    broker_company character varying(200),
    broker_country character varying(10),
    broker_name character varying(200),
    broker_phone character varying(50),
    broker_postcode character varying(20),
    broker_state character varying(120),
    client_code character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    importer_address1 character varying(255),
    importer_address2 character varying(255),
    importer_city character varying(120),
    importer_contact character varying(200),
    importer_country character varying(10),
    importer_name character varying(200),
    importer_phone character varying(50),
    importer_postcode character varying(20),
    importer_state character varying(120),
    updated_at timestamp(6) without time zone NOT NULL,
    broker_id character varying(40),
    broker_license character varying(60),
    currency character varying(3),
    duties_account character varying(60),
    duties_bill_to character varying(20),
    importer_company_reg character varying(60),
    importer_eori character varying(40),
    importer_ioss character varying(40),
    importer_tax_id character varying(60),
    importer_tax_id_type character varying(20),
    incoterms character varying(10),
    reason_for_export character varying(40),
    importer_gstin character varying(40),
    importer_iec character varying(40),
    importer_type character varying(10)
);


--
-- Name: client_customs_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.client_customs_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_customs_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    address_line1 character varying(255),
    city character varying(100),
    client_code character varying(50) NOT NULL,
    country_code character varying(10),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    name character varying(255) NOT NULL,
    notes text,
    phone character varying(50),
    state character varying(50),
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    zip_code character varying(20),
    return_city character varying(100),
    return_country character varying(10),
    return_line1 character varying(255),
    return_line2 character varying(255),
    return_name character varying(255),
    return_phone character varying(50),
    return_state character varying(50),
    return_zip character varying(20),
    return_same_as_ship_from boolean,
    ship_from_line2 character varying(255),
    ship_from_name character varying(255),
    ship_from_phone character varying(50)
);


--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customs_profile_country; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.customs_profile_country (
    profile_id bigint NOT NULL,
    country character varying(2) NOT NULL,
    id bigint NOT NULL,
    client_code character varying(50) NOT NULL
);


--
-- Name: customs_profile_country_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.customs_profile_country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: customs_profile_country_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.customs_profile_country_id_seq OWNED BY public.customs_profile_country.id;


--
-- Name: label_batch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.label_batch (
    order_no integer NOT NULL,
    order_suffix integer,
    order_status character varying(255),
    cust_no character varying(255),
    terms_cd character varying(255),
    shipvia_cd character varying(255),
    ship_addr1 character varying(255),
    shipto_city character varying(255),
    shipto_state character varying(255),
    shipto_zip character varying(255),
    shipto_country_cd character varying(255),
    ship_attn character varying(255),
    ship_name character varying(255),
    country_name character varying(255),
    price numeric(38,2),
    intl_yn character varying(255),
    freight_cost numeric(38,2),
    ff_schema_substr character varying(255),
    tenant_id character varying(255),
    location character varying(255),
    weight numeric(38,2),
    ship_via character varying(255),
    track character varying(255),
    tote_number integer,
    goods_desc character varying(255),
    unit_value integer,
    batch_id integer,
    phone character varying(255),
    created_date date,
    is_processed boolean,
    is_error boolean,
    is_label_generated boolean,
    api_status integer,
    is_manual character varying(255)
);


--
-- Name: order_carrier_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_carrier_details (
    id bigint NOT NULL,
    account_number character varying(100),
    carrier_code character varying(50),
    client_id character varying(255),
    client_secret character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    environment character varying(20),
    order_no integer NOT NULL,
    order_suffix integer,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: order_carrier_details_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_carrier_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_carrier_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_customs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_customs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(3),
    importer_city character varying(100),
    importer_country character varying(10),
    importer_line1 character varying(255),
    importer_line2 character varying(255),
    importer_name character varying(255),
    importer_phone character varying(50),
    importer_state character varying(50),
    importer_zip character varying(20),
    importer_company character varying(255),
    importer_eori character varying(50),
    importer_tax_id character varying(50),
    importer_vat character varying(50),
    incoterms character varying(10),
    notes character varying(500),
    order_no character varying(40) NOT NULL,
    reason_for_export character varying(20),
    updated_at timestamp(6) without time zone NOT NULL,
    weight_unit character varying(3)
);


--
-- Name: order_customs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_customs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_customs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_customs_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_customs_item (
    id bigint NOT NULL,
    country_of_origin character varying(2),
    description character varying(200),
    hs_code character varying(12),
    quantity integer NOT NULL,
    sku character varying(60),
    unit_value numeric(12,2),
    weight numeric(10,3),
    order_customs_id bigint NOT NULL
);


--
-- Name: order_customs_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_customs_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_customs_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_label_tracking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_label_tracking (
    id bigint NOT NULL,
    order_no integer NOT NULL,
    order_suffix integer DEFAULT 0,
    tracking_number character varying(255),
    tracking_url character varying(255),
    ship_via_cd character varying(255),
    is_label_generated boolean DEFAULT false,
    label_generated_at timestamp without time zone,
    label_file_path character varying(255),
    status character varying(255) DEFAULT 'PENDING'::character varying,
    error_message character varying(255),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    carrier character varying(100),
    label_url character varying(500),
    shipping_cost numeric(10,2),
    estimated_delivery date,
    carrier_response text,
    label_pdf bytea,
    account_number character varying(100),
    idempotency_key character varying(100)
);


--
-- Name: order_label_tracking_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.order_label_tracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: order_label_tracking_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.order_label_tracking_id_seq OWNED BY public.order_label_tracking.id;


--
-- Name: order_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_lines (
    id bigint NOT NULL,
    order_no integer NOT NULL,
    tenant_id character varying(50) NOT NULL,
    line_no integer,
    item_no character varying(50),
    item_description text,
    qty_shipped integer DEFAULT 1,
    hs_code character varying(50),
    hs_desc character varying(255),
    description text,
    country_of_origin character varying(10) DEFAULT 'US'::character varying,
    customs_decl_value numeric(10,2),
    unit_price numeric(10,2),
    total_price numeric(10,2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: order_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.order_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: order_lines_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.order_lines_id_seq OWNED BY public.order_lines.id;


--
-- Name: package_preset; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.package_preset (
    id bigint NOT NULL,
    carrier character varying(20),
    carrier_package_code character varying(40),
    created_at timestamp(6) without time zone NOT NULL,
    dim_unit character varying(5) NOT NULL,
    enabled boolean NOT NULL,
    height numeric(8,2),
    is_default boolean NOT NULL,
    kind character varying(10) NOT NULL,
    length numeric(8,2),
    max_weight numeric(8,2),
    name character varying(80) NOT NULL,
    tare_weight numeric(8,2),
    updated_at timestamp(6) without time zone NOT NULL,
    weight_unit character varying(5) NOT NULL,
    width numeric(8,2),
    box_cost numeric(8,2),
    flat_rate boolean,
    internal_height numeric(8,2),
    internal_length numeric(8,2),
    internal_width numeric(8,2),
    sort_order integer,
    origin_country character varying(2),
    source character varying(20),
    scope character varying(15)
);


--
-- Name: package_preset_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.package_preset ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.package_preset_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: service_package; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.service_package (
    id bigint NOT NULL,
    discount_pct numeric(5,2),
    preset_id bigint NOT NULL,
    service_id bigint NOT NULL
);


--
-- Name: service_package_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.service_package ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_package_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ship_vias; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ship_vias (
    id integer NOT NULL,
    shipvia_cd character varying(255),
    shipvia_desc character varying(255),
    vendor_id character varying(255),
    api_base_url character varying(255),
    auth_url character varying(255),
    api_version character varying(255),
    sandbox_url character varying(255),
    logo_url character varying(255),
    is_active boolean DEFAULT true,
    documentation_url character varying(255),
    connection_guide character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


--
-- Name: shipping_service; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipping_service (
    id bigint NOT NULL,
    carrier character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    enabled boolean NOT NULL,
    name character varying(100) NOT NULL,
    scope character varying(15) NOT NULL,
    service_code character varying(40) NOT NULL,
    sort_order integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    origin_country character varying(2),
    source character varying(20),
    synced_at timestamp without time zone,
    max_weight_lb integer,
    max_length_in integer,
    max_length_girth_in integer,
    surcharge_length_girth_in integer
);


--
-- Name: shipping_service_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipping_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipping_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipvia_service_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipvia_service_mapping (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    service_id bigint NOT NULL,
    shipvia_cd character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    client_code character varying(50),
    dest_type character varying(10),
    dest_value text
);


--
-- Name: shipvia_service_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipvia_service_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipvia_service_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    role character varying(100) NOT NULL,
    preferred_carrier character varying(50) DEFAULT 'FEDEX'::character varying,
    carrier_client_id character varying(255),
    carrier_client_secret character varying(255),
    carrier_account_number character varying(100),
    carrier_access_token text,
    carrier_token_expires_at timestamp without time zone,
    carrier_connected boolean DEFAULT false,
    carrier_connected_at timestamp without time zone,
    carrier_environment character varying(20) DEFAULT 'SANDBOX'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: carrier_config id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier_config ALTER COLUMN id SET DEFAULT nextval('public.carrier_config_id_seq'::regclass);


--
-- Name: customs_profile_country id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customs_profile_country ALTER COLUMN id SET DEFAULT nextval('public.customs_profile_country_id_seq'::regclass);


--
-- Name: order_label_tracking id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_label_tracking ALTER COLUMN id SET DEFAULT nextval('public.order_label_tracking_id_seq'::regclass);


--
-- Name: order_lines id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_lines ALTER COLUMN id SET DEFAULT nextval('public.order_lines_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: carrier_account_ref; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.carrier_account_ref (id, account_name, account_number, active, carrier_code, client_id, client_secret, created_at, customer_no, environment, is_default, updated_at, last_verified_at, verified, client_default) FROM stdin;
11	FedEx Sandbox	740561111	t	FEDEX	l71fa9c1d783c44780ad128ba6d7ec804f	67416d4dd23145768c36454b221e196a	2026-07-13 19:29:49.772558	ARHDEV	SANDBOX	f	2026-07-16 18:58:27.390335	2026-07-14 22:17:19.221084	t	t
16	Test UPS	VAL-UPS-1	t	UPS	746W05	N9zxIJT4kkdkfWj4WFOh5zpXWDzOErW3GwNIounGNgOdgXqy	2026-07-15 13:36:45.517891	ARHDEV	SANDBOX	f	2026-07-16 18:58:27.394129	\N	\N	f
12	USPS via Stamps	STAMPS_ACCOUNT	t	USPS	3grGAxufCUikogr8J7D5Nu5xtzoMC7WC	mOru4UUIiNYvErTPn0dhT85qReqBjaf2i_kZUEoVmCass8XeluykZ1k5uMEpjE19	2026-07-13 19:29:49.866327	\N	SANDBOX	f	2026-07-13 21:42:55.64659	\N	\N	f
10	UPS Sandbox	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	t	UPS	746W05	N9zxIJT4kkdkfWj4WFOh5zpXWDzOErW3GwNIounGNgOdgXqy	2026-07-13 19:29:49.706185	\N	SANDBOX	f	2026-07-15 13:34:52.630376	\N	\N	f
20	Chrome Test UPS	740009999	t	UPS	746W05	N9zxIJT4kkdkfWj4WFOh5zpXWDzOErW3GwNIounGNgOdgXqy	2026-07-20 18:33:46.329186	CHROMECO	SANDBOX	f	2026-07-20 18:33:46.329197	\N	\N	t
21	Test UPS #2	VAL-UPS-2	t	UPS	746W05	N9zxIJT4kkdkfWj4WFOh5zpXWDzOErW3GwNIounGNgOdgXqy	2026-07-20 19:09:31.656687	ARHDEV	SANDBOX	\N	2026-07-20 19:09:31.656687	\N	\N	t
\.


--
-- Data for Name: carrier_config; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.carrier_config (id, user_id, carrier_code, client_id, client_secret, account_number, access_token, token_expiry, environment, is_active, created_at, updated_at, carrier_name, token_expires_at, ship_via_id, tenant_id, account_code, is_default) FROM stdin;
28	5	UPS	746W05	N9zxIJT4kkdkfWj4WFOh5zpXWDzOErW3GwNIounGNgOdgXqy	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	ups-local-02dd15cffeee3c36	\N	SANDBOX	t	2026-07-14 14:55:50.887821	2026-07-14 14:56:13.6072	UPS	2026-07-14 10:26:13.603015	149	\N	\N	f
\.


--
-- Data for Name: client_customs_profile; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.client_customs_profile (id, account_carrier, account_no, broker_address1, broker_address2, broker_city, broker_company, broker_country, broker_name, broker_phone, broker_postcode, broker_state, client_code, created_at, importer_address1, importer_address2, importer_city, importer_contact, importer_country, importer_name, importer_phone, importer_postcode, importer_state, updated_at, broker_id, broker_license, currency, duties_account, duties_bill_to, importer_company_reg, importer_eori, importer_ioss, importer_tax_id, importer_tax_id_type, incoterms, reason_for_export, importer_gstin, importer_iec, importer_type) FROM stdin;
14	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	UKSTYLE	2026-07-17 18:54:37.509814	\N	\N	\N	\N	\N	\N	\N	\N	\N	2026-07-17 18:54:37.509837	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	RECEIVER
16	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	EUROMODA	2026-07-17 18:57:18.706499	Bahnhofstrasse 5	\N	Zurich	\N	CH	Alpine Trade AG	\N	\N	\N	2026-07-17 18:57:18.706515	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	BUSINESS
17	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	INDTECH	2026-07-17 18:58:57.606154	Sheikh Zayed Road 12	\N	Dubai	\N	AE	Gulf Gateway Trading LLC	\N	\N	\N	2026-07-17 18:58:57.606196	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	BUSINESS
18	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	QAACME	2026-07-17 19:03:04.41585	Marine Drive 1	\N	Mumbai	\N	IN	Bharat Trade Pvt Ltd	\N	\N	\N	2026-07-17 19:03:04.415901	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	27AAAPA1234A1Z5	0512345678	BUSINESS
13	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	UKSTYLE	2026-07-17 18:52:01.262834	10 Rue du Commerce	\N	Lyon	\N	FR	La Maison Import SARL	\N	\N	\N	2026-07-17 19:14:05.443504	\N	\N	\N	\N	\N	\N	FR12345678901	\N	\N	\N	\N	\N	\N	\N	BUSINESS
15	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	EUROMODA	2026-07-17 18:56:03.368778	1 Bond St	\N	London	\N	GB	Britannia Imports Ltd	\N	\N	\N	2026-07-17 19:27:55.693809	\N	\N	GBP	DUTY-ACC-9001	THIRD_PARTY	\N	\N	\N	\N	\N	DDP	Sale	\N	\N	BUSINESS
20	\N	\N	9 Warehouse Rd	\N	Austin	Acme Distribution	US	Acme Distribution	512-555-0142	73301	TX	QAACME	2026-07-17 19:46:22.340546	10 Rue du Commerce	\N	Paris	Claire Fontaine	FR	La Maison Import SARL	+33-1-4455-6677	75015	\N	2026-07-17 19:46:22.340553	\N	\N	USD	\N	SENDER	RCS 403 032 650	FR40303265045	\N	FR40303265045	VAT	FCA	Gift	\N	\N	BUSINESS
21	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	\N	QAACME	2026-07-20 18:45:26.389084	Friedrichstrasse 100	\N	Berlin	Klaus Fischer	DE	Chrome Test Import GmbH	49-30-555-9000	10117	\N	2026-07-20 18:45:26.389105	\N	\N	\N	\N	\N	\N	DE999888777	\N	\N	VAT	\N	\N	\N	\N	BUSINESS
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clients (id, address_line1, city, client_code, country_code, created_at, email, name, notes, phone, state, status, updated_at, zip_code, return_city, return_country, return_line1, return_line2, return_name, return_phone, return_state, return_zip, return_same_as_ship_from, ship_from_line2, ship_from_name, ship_from_phone) FROM stdin;
1	9 Warehouse Rd	Syracuse	ARHDEV	US	2026-07-14 15:42:44.777627	ops@arhdev.com	ARH Development	\N	315-555-0142	NY	ACTIVE	2026-07-17 18:43:10.20084	13201	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	ARH Development	315-555-0142
7	9 Warehouse Rd	Austin	QAACME	US	2026-07-15 18:36:54.079673	ship@acmedist.com	Acme Distribution	\N	512-555-0142	TX	ACTIVE	2026-07-17 18:43:10.250065	73301	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	Acme Distribution	512-555-0142
9	22 Carnaby Street	London	UKSTYLE	GB	2026-07-17 18:43:10.307848	orders@ukstyle.co.uk	UK Style House	\N	+44-20-7946-0011	\N	ACTIVE	2026-07-17 18:43:10.307856	W1F 7DE	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	UK Style House	+44-20-7946-0011
10	Plot 14 SEEPZ	Mumbai	INDTECH	IN	2026-07-17 18:43:10.365529	exports@indtech.in	IndTech Electronics	\N	+91-22-4000-1234	MH	ACTIVE	2026-07-17 18:43:10.365538	400096	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	IndTech Electronics	+91-22-4000-1234
11	88 Bondi Road	Sydney	AUSSURF	AU	2026-07-17 18:43:10.425723	ship@aussiesurf.au	Aussie Surf Co	\N	+61-2-9000-7777	NSW	ACTIVE	2026-07-17 18:43:10.425735	2026	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	Aussie Surf Co	+61-2-9000-7777
12	Kurfuerstendamm 45	Berlin	EUROMODA	DE	2026-07-17 18:43:10.493623	versand@euromoda.de	EuroModa GmbH	\N	+49-30-555-8800	BE	ACTIVE	2026-07-17 18:43:10.493633	10719	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	EuroModa GmbH	+49-30-555-8800
13	500 Silicon Way	San Jose	CHROMECO	US	2026-07-20 18:32:00.940646	ops@chrometestco.com	Chrome Test Co	\N	555-000-1111	CA	ACTIVE	2026-07-20 18:32:00.941459	95101	\N	\N	\N	\N	\N	\N	\N	\N	t	\N	Chrome Test Warehouse	\N
\.


--
-- Data for Name: customs_profile_country; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.customs_profile_country (profile_id, country, id, client_code) FROM stdin;
13	FR	19	UKSTYLE
14	US	20	UKSTYLE
15	GB	21	EUROMODA
16	CH	22	EUROMODA
17	AE	23	INDTECH
17	SA	24	INDTECH
18	IN	25	QAACME
20	FR	27	QAACME
21	DE	28	QAACME
\.


--
-- Data for Name: label_batch; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.label_batch (order_no, order_suffix, order_status, cust_no, terms_cd, shipvia_cd, ship_addr1, shipto_city, shipto_state, shipto_zip, shipto_country_cd, ship_attn, ship_name, country_name, price, intl_yn, freight_cost, ff_schema_substr, tenant_id, location, weight, ship_via, track, tote_number, goods_desc, unit_value, batch_id, phone, created_date, is_processed, is_error, is_label_generated, api_status, is_manual) FROM stdin;
11156	0	S	ARHDEV	DUE	P80	202 Main St                   	ALBANY	NY	12207	US	Valued Customer	3	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	1.13	P80	                                                  	101	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11157	0	S	ARHDEV	DUE	P80	203 Main St                   	SYRACUSE	NY	13202	US	Valued Customer	4	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	0.90	P80	                                                  	102	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11159	0	S	ARHDEV	DUE	P80	205 Main St                   	ALBANY	NY	12207	US	Valued Customer	6	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	0.68	P80	                                                  	103	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11161	0	S	ARHDEV	DUE	P80	207 Main St                   	SYRACUSE	NY	13202	US	Valued Customer	8	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	0.16	P80	                                                  	104	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11162	0	S	ARHDEV	DUE	P80	208 Main St                   	SYRACUSE	NY	13202	US	Valued Customer	9	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	1.24	P80	                                                  	105	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11153	0	S	ARHDEV	DUE	P80	Hauptstrasse 5	BERLIN	NY	10115	CA	Valued Customer	Hans Müller	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	1.24	P80	                                                  	100	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11155	0	S	ARHDEV	DUE	P80	201 Main St                   	BUFFALO	NY	14228	US	Valued Customer	2	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	0.68	P80	                                                  	133	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11158	0	S	ARHDEV	DUE	P80	204 Main St                   	SYRACUSE	NY	13202	US	Valued Customer	5	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	0.16	P80	                                                  	136	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11188	0	S	EUROMODA	\N	P80	18 Rue de Rivoli	PARIS		75001	FR	Sophie Laurent	Sophie Laurent	France	\N	Y	\N	\N	EUROMODA	\N	1.00	\N	\N	\N	Fashion	\N	71	+33-1-4477-0102	2026-07-17	f	f	f	\N	\N
11154	0	S	ARHDEV	DUE	P80	200 Main St                   	BUFFALO	NY	14228	US	Valued Customer	1	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	0.16	P80	                                                  	140	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11160	0	S	ARHDEV	DUE	P80	206 Main St                   	BUFFALO	NY	14228	US	Valued Customer	7	United States	\N	N	0.00	ARHDEV	ARHDEV	ARDTC	0.16	P80	                                                  	130	Upholstery Fabric	1	67	6167723513	2026-07-02	f	f	f	0	B
11170	0	S	QAACME	\N	P80	Friedrichstrasse 12	BERLIN	BE	10117	DE	Hans Weber	Hans Weber	Germany	\N	Y	\N	\N	QAACME	\N	2.40	\N	\N	\N	Office Furniture	\N	70	49-30-555-0100	2026-07-16	f	f	f	\N	\N
11181	0	S	UKSTYLE	\N	F77	350 5th Ave	NEW YORK	NY	10118	US	Mark Reed	Mark Reed	United States	\N	Y	\N	\N	UKSTYLE	\N	1.50	\N	\N	\N	Apparel	\N	71	212-555-0187	2026-07-17	f	f	f	\N	\N
11182	0	S	INDTECH	\N	P80	Sheikh Zayed Rd 12	DUBAI		00000	AE	Omar Hassan	Omar Hassan	United Arab Emirates	\N	Y	\N	\N	INDTECH	\N	0.80	\N	\N	\N	Electronics	\N	71	+971-4-555-0122	2026-07-17	f	f	f	\N	\N
11183	0	S	INDTECH	\N	F77	1 Tech Way	SAN JOSE	CA	95110	US	Priya Nair	Priya Nair	United States	\N	Y	\N	\N	INDTECH	\N	0.60	\N	\N	\N	Electronics	\N	71	408-555-0170	2026-07-17	f	f	f	\N	\N
11184	0	S	AUSSURF	\N	P80	5 Queen Street	AUCKLAND		1010	NZ	Tom Baker	Tom Baker	New Zealand	\N	Y	\N	\N	AUSSURF	\N	4.20	\N	\N	\N	Sporting goods	\N	71	+64-9-555-0133	2026-07-17	f	f	f	\N	\N
11185	0	S	EUROMODA	\N	P80	10 Savile Row	LONDON		W1S 3PF	GB	Emma Clarke	Emma Clarke	United Kingdom	\N	Y	\N	\N	EUROMODA	\N	1.10	\N	\N	\N	Fashion	\N	71	+44-20-7946-0155	2026-07-17	f	f	f	\N	\N
11187	0	S	QAACME	\N	P80	Marine Drive 7	MUMBAI	MH	400020	IN	Rahul Mehta	Rahul Mehta	India	\N	Y	\N	\N	QAACME	\N	2.90	\N	\N	\N	Office Furniture	\N	71	+91-22-5550-0199	2026-07-17	f	f	f	\N	\N
11186	0	S	EUROMODA	\N	F77	Bahnhofstrasse 20	ZURICH		8001	CH	Lukas Meier	Lukas Meier	Switzerland	\N	Y	\N	\N	EUROMODA	\N	1.30	\N	\N	\N	Fashion	\N	71	+41-44-555-0166	2026-07-17	f	f	f	\N	\N
11180	0	S	UKSTYLE	\N	P80	18 Rue de Rivoli	PARIS		75001	FR	Claire Dubois	Claire Dubois	France	\N	Y	\N	\N	UKSTYLE	\N	1.20	\N	\N	\N	Apparel	\N	71	+33-1-4477-0101	2026-07-17	f	f	f	\N	\N
\.


--
-- Data for Name: order_carrier_details; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_carrier_details (id, account_number, carrier_code, client_id, client_secret, created_at, environment, order_no, order_suffix, updated_at) FROM stdin;
13	740561111	\N	\N	\N	2026-07-13 19:31:51.790419	\N	11155	0	2026-07-13 19:31:51.790419
14	740561111	\N	\N	\N	2026-07-13 19:31:51.790419	\N	11156	0	2026-07-13 19:31:51.790419
15	CLIENT-ACCT-999	\N	\N	\N	2026-07-13 19:31:51.793784	\N	11157	0	2026-07-13 19:31:51.793784
16	CLIENT-ACCT-999	\N	\N	\N	2026-07-13 19:31:51.793784	\N	11158	0	2026-07-13 19:31:51.793784
11	740561111	FEDEX	l71fa9c1d783c44780ad128ba6d7ec804f	67416d4dd23145768c36454b221e196a	2026-07-13 19:31:51.781935	SANDBOX	11153	0	2026-07-13 19:31:51.781935
12	740561111	FEDEX	l71fa9c1d783c44780ad128ba6d7ec804f	67416d4dd23145768c36454b221e196a	2026-07-13 19:31:51.781935	SANDBOX	11154	0	2026-07-13 19:31:51.781935
\.


--
-- Data for Name: order_customs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_customs (id, created_at, currency, importer_city, importer_country, importer_line1, importer_line2, importer_name, importer_phone, importer_state, importer_zip, importer_company, importer_eori, importer_tax_id, importer_vat, incoterms, notes, order_no, reason_for_export, updated_at, weight_unit) FROM stdin;
\.


--
-- Data for Name: order_customs_item; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_customs_item (id, country_of_origin, description, hs_code, quantity, sku, unit_value, weight, order_customs_id) FROM stdin;
\.


--
-- Data for Name: order_label_tracking; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_label_tracking (id, order_no, order_suffix, tracking_number, tracking_url, ship_via_cd, is_label_generated, label_generated_at, label_file_path, status, error_message, created_at, updated_at, carrier, label_url, shipping_cost, estimated_delivery, carrier_response, label_pdf, account_number, idempotency_key) FROM stdin;
101	11155	0	781883678859	https://www.fedex.com/fedextrack/?trknbr=781883678859	P80	t	2026-07-15 12:47:21.835867	https://labels.local/fedex/781883678859.pdf	GENERATED	\N	2026-07-15 12:47:21.835905	2026-07-15 12:47:21.835907	\N	\N	\N	\N	\N	\N	740561111	2124e63d-c1e7-46a7-a8cc-c246e449e0b3
107	11160	0	783504009314	https://www.fedex.com/fedextrack/?trknbr=783504009314	P80	t	2026-07-16 19:00:12.714998	https://labels.local/fedex/783504009314.pdf	GENERATED	\N	2026-07-16 19:00:12.715026	2026-07-16 19:00:12.715029	\N	\N	\N	\N	\N	\N	740561111	14739eeb-8598-43c8-8acc-7f597e496897
110	11184	0	1Z114a4c2def75fdd6	https://www.ups.com/track?tracknum=1Z114a4c2def75fdd6	P80	t	2026-07-17 19:07:48.992794	https://labels.local/ups/1Z114a4c2def75fdd6.pdf	GENERATED	\N	2026-07-17 19:07:48.992812	2026-07-17 19:07:48.992814	\N	\N	\N	\N	\N	\N	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	07df8331-7eb3-4d91-80f8-22170a0d8998
112	11181	0	1Zb32fa4177307a908	https://www.ups.com/track?tracknum=1Zb32fa4177307a908	F77	t	2026-07-17 19:09:26.490647	https://labels.local/ups/1Zb32fa4177307a908.pdf	GENERATED	\N	2026-07-17 19:09:26.490657	2026-07-17 19:09:26.490659	\N	\N	\N	\N	\N	\N	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	649917c2-72e2-4095-bc28-8624cd47f979
113	11185	0	1Z22e4f8577caa1798	https://www.ups.com/track?tracknum=1Z22e4f8577caa1798	P80	t	2026-07-17 19:25:43.688655	https://labels.local/ups/1Z22e4f8577caa1798.pdf	GENERATED	\N	2026-07-17 19:25:43.688659	2026-07-17 19:25:43.68866	\N	\N	\N	\N	\N	\N	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	8c15cfe6-78e6-47df-a61d-e6c7044b9491
117	11154	0	788758360227	https://www.fedex.com/fedextrack/?trknbr=788758360227	P80	t	2026-07-20 18:35:06.537499	https://labels.local/fedex/788758360227.pdf	GENERATED	\N	2026-07-20 18:35:06.537539	2026-07-20 18:35:06.537541	\N	\N	\N	\N	\N	\N	740561111	7dc0e42e-bb9e-48b7-9709-6240129235a7
102	11153	0	780049687590	https://www.fedex.com/fedextrack/?trknbr=780049687590	P80	t	2026-07-15 14:49:16.175491	https://labels.local/fedex/780049687590.pdf	GENERATED	\N	2026-07-15 14:49:16.175514	2026-07-15 14:49:16.175516	\N	\N	\N	\N	\N	\N	740561111	e127bc3f-30c7-48bf-80df-87bf2dbe75f5
103	11159	0	1Z249ecf6fcd54c990	https://www.ups.com/track?tracknum=1Z249ecf6fcd54c990	P80	t	2026-07-15 14:53:44.172508	https://labels.local/ups/1Z249ecf6fcd54c990.pdf	GENERATED	\N	2026-07-15 14:53:44.172517	2026-07-15 14:53:44.172519	\N	\N	\N	\N	\N	\N	VAL-UPS-1	317f7eb5-d180-4db3-a313-87cfb08c47cb
111	11180	0	1Z1d9948173e60ef0b	https://www.ups.com/track?tracknum=1Z1d9948173e60ef0b	P80	t	2026-07-17 19:08:28.809767	https://labels.local/ups/1Z1d9948173e60ef0b.pdf	GENERATED	\N	2026-07-17 19:08:28.809773	2026-07-17 19:08:28.809775	\N	\N	\N	\N	\N	\N	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	9ded0eec-20cb-49b4-b083-3e8be51cca36
118	11170	0	1Z6ceff896a0555e3d	https://www.ups.com/track?tracknum=1Z6ceff896a0555e3d	P80	t	2026-07-20 18:46:09.459662	https://labels.local/ups/1Z6ceff896a0555e3d.pdf	GENERATED	\N	2026-07-20 18:46:09.459665	2026-07-20 18:46:09.459666	\N	\N	\N	\N	\N	\N	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	45b34cbe-3d6a-43ba-8a31-4d10106188d6
122	11161	0	1Zd77572697535496f	https://www.ups.com/track?tracknum=1Zd77572697535496f	P80	t	2026-07-20 22:03:27.554352	https://labels.local/ups/1Zd77572697535496f.pdf	GENERATED	\N	2026-07-20 22:03:27.554382	2026-07-20 22:03:27.554386	\N	\N	\N	\N	\N	\N	VAL-UPS-1	024584eb-b7c4-44ed-bc08-a49218d98b3c
\.


--
-- Data for Name: order_lines; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.order_lines (id, order_no, tenant_id, line_no, item_no, item_description, qty_shipped, hs_code, hs_desc, description, country_of_origin, customs_decl_value, unit_price, total_price, created_at, updated_at) FROM stdin;
69	11153	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
70	11153	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
71	11153	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
72	11156	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
73	11156	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
74	11156	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
75	11157	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
76	11157	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
77	11157	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
78	11159	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
79	11159	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
80	11159	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
81	11161	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
82	11161	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
83	11161	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
84	11162	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
85	11162	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
86	11162	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
87	11160	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
88	11160	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
89	11160	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
90	11155	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
91	11155	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
92	11155	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
93	11158	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
94	11158	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
95	11158	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
96	11154	ARHDEV	1	SKU-1001	Cotton Crew T-Shirt	5	6109.10.00	Cotton apparel	SALE	IN	45.00	9.00	45.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
97	11154	ARHDEV	2	SKU-2044	Leather Bifold Wallet	2	4202.31.00	Leather goods	SALE	IN	37.00	18.50	37.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
98	11154	ARHDEV	3	SKU-3090	Ceramic Coffee Mug	4	6912.00.48	Ceramic tableware	SALE	CN	25.00	6.25	25.00	2026-07-13 19:26:26.903125	2026-07-13 19:26:26.903125
99	11170	QAACME	1	CH-1000	Ergonomic office chair	2	940130	Seats, swivel	\N	US	180.00	180.00	360.00	2026-07-16 17:20:47.310196	2026-07-16 17:20:47.310196
100	11170	QAACME	2	DK-2000	Standing desk	1	940310	Metal office furniture	\N	US	420.00	420.00	420.00	2026-07-16 17:20:47.310196	2026-07-16 17:20:47.310196
101	11180	UKSTYLE	1	WL-100	Wool coat	1	620111	Wool overcoats	Wool coat	GB	240.00	240.00	240.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
102	11180	UKSTYLE	2	SC-200	Silk scarf	2	621410	Silk scarves	Silk scarf	GB	45.00	45.00	90.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
103	11181	UKSTYLE	1	WL-100	Wool coat	2	620111	Wool overcoats	Wool coat	GB	240.00	240.00	480.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
104	11182	INDTECH	1	SS-10	Smart sensor module	5	853690	Electrical apparatus	Smart sensor module	IN	32.00	32.00	160.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
105	11183	INDTECH	1	CB-20	Controller board	3	853710	Control boards	Controller board	IN	85.00	85.00	255.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
106	11183	INDTECH	2	SS-10	Smart sensor module	4	853690	Electrical apparatus	Smart sensor module	IN	32.00	32.00	128.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
107	11184	AUSSURF	1	SB-01	Surfboard 7ft	1	950629	Water-sport equipment	Surfboard 7ft	AU	520.00	520.00	520.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
108	11185	EUROMODA	1	DR-77	Designer dress	2	620443	Dresses synthetic	Designer dress	DE	310.00	310.00	620.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
109	11186	EUROMODA	1	HB-88	Leather handbag	1	420221	Leather handbags	Leather handbag	DE	450.00	450.00	450.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
110	11187	QAACME	1	CH-1000	Ergonomic office chair	2	940130	Swivel seats	Ergonomic office chair	US	180.00	180.00	360.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
111	11187	QAACME	2	DK-2000	Standing desk	1	940310	Metal office furniture	Standing desk	US	420.00	420.00	420.00	2026-07-17 18:43:36.147242	2026-07-17 18:43:36.147242
112	11188	EUROMODA	1	DR-77	Designer dress	1	620443	Dresses synthetic	Designer dress	DE	310.00	310.00	310.00	2026-07-17 21:52:21.752323	2026-07-17 21:52:21.752323
\.


--
-- Data for Name: package_preset; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.package_preset (id, carrier, carrier_package_code, created_at, dim_unit, enabled, height, is_default, kind, length, max_weight, name, tare_weight, updated_at, weight_unit, width, box_cost, flat_rate, internal_height, internal_length, internal_width, sort_order, origin_country, source, scope) FROM stdin;
27	USPS	MD_FLAT_RATE_BOX	2026-07-20 21:32:41.625378	IN	t	6.00	f	CARRIER	11.25	70.00	USPS Medium Flat Rate Box	\N	2026-07-20 21:32:41.625404	LB	8.75	\N	t	\N	\N	\N	102	US	CARRIER_SYNC	DOMESTIC
28	USPS	LG_FLAT_RATE_BOX	2026-07-20 21:32:41.632416	IN	t	6.00	f	CARRIER	12.25	70.00	USPS Large Flat Rate Box	\N	2026-07-20 21:32:41.632441	LB	12.00	\N	t	\N	\N	\N	103	US	CARRIER_SYNC	DOMESTIC
29	UPS	01	2026-07-20 21:36:58.815401	IN	t	0.50	f	CARRIER	12.50	1.00	UPS Letter	\N	2026-07-20 21:36:58.815433	LB	9.50	\N	f	\N	\N	\N	100	DE	CARRIER_SYNC	BOTH
30	UPS	04	2026-07-20 21:36:58.823445	IN	t	2.00	f	CARRIER	16.00	3.00	UPS Express Pak	\N	2026-07-20 21:36:58.823456	LB	12.75	\N	f	\N	\N	\N	101	DE	CARRIER_SYNC	BOTH
31	UPS	03	2026-07-20 21:36:58.82801	IN	t	6.00	f	CARRIER	38.00	\N	UPS Tube	\N	2026-07-20 21:36:58.828032	LB	6.00	\N	f	\N	\N	\N	102	DE	CARRIER_SYNC	BOTH
32	UPS	2a	2026-07-20 21:36:58.834375	IN	t	2.00	f	CARRIER	13.00	\N	UPS Small Express Box	\N	2026-07-20 21:36:58.834394	LB	11.00	\N	f	\N	\N	\N	103	DE	CARRIER_SYNC	BOTH
33	UPS	2b	2026-07-20 21:36:58.840171	IN	t	3.00	f	CARRIER	15.00	\N	UPS Medium Express Box	\N	2026-07-20 21:36:58.840181	LB	11.00	\N	f	\N	\N	\N	104	DE	CARRIER_SYNC	BOTH
34	UPS	2c	2026-07-20 21:36:58.846055	IN	t	3.00	f	CARRIER	18.00	\N	UPS Large Express Box	\N	2026-07-20 21:36:58.846066	LB	13.00	\N	f	\N	\N	\N	105	DE	CARRIER_SYNC	BOTH
35	UPS	25	2026-07-20 21:36:58.852846	IN	t	10.75	f	CARRIER	16.50	22.00	UPS 10KG Box	\N	2026-07-20 21:36:58.852861	LB	13.25	\N	t	\N	\N	\N	106	DE	CARRIER_SYNC	INTERNATIONAL
36	UPS	24	2026-07-20 21:36:58.85776	IN	t	10.75	f	CARRIER	16.50	55.00	UPS 25KG Box	\N	2026-07-20 21:36:58.857771	LB	13.25	\N	t	\N	\N	\N	107	DE	CARRIER_SYNC	INTERNATIONAL
37	FEDEX	FEDEX_ENVELOPE	2026-07-20 21:36:58.878303	IN	t	0.50	f	CARRIER	12.50	1.00	FedEx Envelope	\N	2026-07-20 21:36:58.878314	LB	9.50	\N	f	\N	\N	\N	100	DE	CARRIER_SYNC	BOTH
38	FEDEX	FEDEX_PAK	2026-07-20 21:36:58.886083	IN	t	1.50	f	CARRIER	15.50	3.00	FedEx Pak	\N	2026-07-20 21:36:58.886101	LB	12.00	\N	f	\N	\N	\N	101	DE	CARRIER_SYNC	BOTH
39	FEDEX	FEDEX_TUBE	2026-07-20 21:36:58.891151	IN	t	6.00	f	CARRIER	38.00	\N	FedEx Tube	\N	2026-07-20 21:36:58.89116	LB	6.00	\N	f	\N	\N	\N	102	DE	CARRIER_SYNC	BOTH
40	FEDEX	FEDEX_10KG_BOX	2026-07-20 21:36:58.898748	IN	t	10.19	f	CARRIER	15.81	22.00	FedEx 10kg Box	\N	2026-07-20 21:36:58.898763	LB	12.94	\N	t	\N	\N	\N	103	DE	CARRIER_SYNC	INTERNATIONAL
41	FEDEX	FEDEX_25KG_BOX	2026-07-20 21:36:58.904863	IN	t	13.19	f	CARRIER	21.56	55.00	FedEx 25kg Box	\N	2026-07-20 21:36:58.904877	LB	16.56	\N	t	\N	\N	\N	104	DE	CARRIER_SYNC	INTERNATIONAL
3	\N	\N	2026-07-18 11:32:25.746359	IN	t	12.00	f	CUSTOM	20.00	50.00	Large Box	1.00	2026-07-18 11:32:25.746403	LB	16.00	\N	\N	\N	\N	\N	\N	\N	SEEDED	BOTH
21	FEDEX	FEDEX_SMALL_BOX	2026-07-20 21:32:40.035242	IN	t	1.50	f	CARRIER	12.38	50.00	FedEx Small Box (One Rate)	\N	2026-07-20 22:01:08.434463	LB	10.88	\N	t	\N	\N	\N	105	US	CARRIER_SYNC	DOMESTIC
22	FEDEX	FEDEX_MEDIUM_BOX	2026-07-20 21:32:40.044237	IN	t	2.38	f	CARRIER	13.25	50.00	FedEx Medium Box (One Rate)	\N	2026-07-20 22:01:08.463045	LB	11.50	\N	t	\N	\N	\N	106	US	CARRIER_SYNC	DOMESTIC
6	\N	\N	2026-07-18 13:25:40.375219	IN	t	35.00	f	CUSTOM	60.00	140.00	Freight Crate	\N	2026-07-18 13:25:40.375287	LB	40.00	\N	\N	\N	\N	\N	\N	\N	SEEDED	BOTH
7	\N	\N	2026-07-18 13:25:40.47827	IN	t	28.00	f	CUSTOM	40.00	90.00	Big Surcharge Box	\N	2026-07-18 13:25:40.478314	LB	30.00	4.50	\N	\N	\N	\N	5	\N	SEEDED	BOTH
2	\N	\N	2026-07-18 11:32:25.739534	IN	t	8.00	t	CUSTOM	16.00	20.00	Medium Box	0.60	2026-07-18 14:54:25.404981	LB	12.00	\N	\N	\N	\N	\N	\N	\N	SEEDED	BOTH
1	\N	\N	2026-07-18 11:32:25.729695	IN	t	4.00	f	CUSTOM	12.00	5.00	Small Box	0.30	2026-07-18 14:54:25.424289	LB	9.00	\N	\N	\N	\N	\N	\N	\N	SEEDED	BOTH
23	FEDEX	FEDEX_LARGE_BOX	2026-07-20 21:32:40.051785	IN	t	3.00	f	CARRIER	17.88	50.00	FedEx Large Box (One Rate)	\N	2026-07-20 22:01:08.469116	LB	12.38	\N	t	\N	\N	\N	107	US	CARRIER_SYNC	DOMESTIC
24	FEDEX	FEDEX_EXTRA_LARGE_BOX	2026-07-20 21:32:40.057218	IN	t	10.75	f	CARRIER	11.88	50.00	FedEx Extra Large Box (One Rate)	\N	2026-07-20 22:01:08.473316	LB	11.00	\N	t	\N	\N	\N	108	US	CARRIER_SYNC	DOMESTIC
4	UPS	01	2026-07-18 11:32:25.751509	IN	t	0.50	f	CARRIER	12.50	1.00	UPS Letter	\N	2026-07-20 21:32:39.813348	LB	9.50	\N	f	\N	\N	\N	100	US	CARRIER_SYNC	BOTH
10	UPS	04	2026-07-20 21:32:39.846344	IN	t	2.00	f	CARRIER	16.00	3.00	UPS Express Pak	\N	2026-07-20 21:32:39.846415	LB	12.75	\N	f	\N	\N	\N	101	US	CARRIER_SYNC	BOTH
11	UPS	03	2026-07-20 21:32:39.872553	IN	t	6.00	f	CARRIER	38.00	\N	UPS Tube	\N	2026-07-20 21:32:39.872572	LB	6.00	\N	f	\N	\N	\N	102	US	CARRIER_SYNC	BOTH
12	UPS	2a	2026-07-20 21:32:39.882769	IN	t	2.00	f	CARRIER	13.00	\N	UPS Small Express Box	\N	2026-07-20 21:32:39.882788	LB	11.00	\N	f	\N	\N	\N	103	US	CARRIER_SYNC	BOTH
13	UPS	2b	2026-07-20 21:32:39.889268	IN	t	3.00	f	CARRIER	15.00	\N	UPS Medium Express Box	\N	2026-07-20 21:32:39.889288	LB	11.00	\N	f	\N	\N	\N	104	US	CARRIER_SYNC	BOTH
14	UPS	2c	2026-07-20 21:32:39.89795	IN	t	3.00	f	CARRIER	18.00	\N	UPS Large Express Box	\N	2026-07-20 21:32:39.897973	LB	13.00	\N	f	\N	\N	\N	105	US	CARRIER_SYNC	BOTH
15	UPS	25	2026-07-20 21:32:39.905578	IN	t	10.75	f	CARRIER	16.50	22.00	UPS 10KG Box	\N	2026-07-20 21:32:39.9056	LB	13.25	\N	t	\N	\N	\N	106	US	CARRIER_SYNC	INTERNATIONAL
16	UPS	24	2026-07-20 21:32:39.917242	IN	t	10.75	f	CARRIER	16.50	55.00	UPS 25KG Box	\N	2026-07-20 21:32:39.917297	LB	13.25	\N	t	\N	\N	\N	107	US	CARRIER_SYNC	INTERNATIONAL
17	FEDEX	FEDEX_ENVELOPE	2026-07-20 21:32:39.988755	IN	t	0.50	f	CARRIER	12.50	1.00	FedEx Envelope	\N	2026-07-20 21:32:39.988793	LB	9.50	\N	f	\N	\N	\N	100	US	CARRIER_SYNC	BOTH
5	FEDEX	FEDEX_PAK	2026-07-18 11:32:25.758849	IN	t	1.50	f	CARRIER	15.50	3.00	FedEx Pak	\N	2026-07-20 21:32:40.002986	LB	12.00	\N	f	\N	\N	\N	101	US	CARRIER_SYNC	BOTH
18	FEDEX	FEDEX_TUBE	2026-07-20 21:32:40.007682	IN	t	6.00	f	CARRIER	38.00	\N	FedEx Tube	\N	2026-07-20 21:32:40.007712	LB	6.00	\N	f	\N	\N	\N	102	US	CARRIER_SYNC	BOTH
19	FEDEX	FEDEX_10KG_BOX	2026-07-20 21:32:40.017481	IN	t	10.19	f	CARRIER	15.81	22.00	FedEx 10kg Box	\N	2026-07-20 21:32:40.017508	LB	12.94	\N	t	\N	\N	\N	103	US	CARRIER_SYNC	INTERNATIONAL
20	FEDEX	FEDEX_25KG_BOX	2026-07-20 21:32:40.025149	IN	t	13.19	f	CARRIER	21.56	55.00	FedEx 25kg Box	\N	2026-07-20 21:32:40.025196	LB	16.56	\N	t	\N	\N	\N	104	US	CARRIER_SYNC	INTERNATIONAL
25	USPS	FLAT_RATE_ENVELOPE	2026-07-20 21:32:41.612557	IN	t	0.50	f	CARRIER	12.50	70.00	USPS Flat Rate Envelope	\N	2026-07-20 21:32:41.612607	LB	9.50	\N	t	\N	\N	\N	100	US	CARRIER_SYNC	DOMESTIC
26	USPS	SM_FLAT_RATE_BOX	2026-07-20 21:32:41.620416	IN	t	1.75	f	CARRIER	8.69	70.00	USPS Small Flat Rate Box	\N	2026-07-20 21:32:41.620435	LB	5.44	\N	t	\N	\N	\N	101	US	CARRIER_SYNC	DOMESTIC
\.


--
-- Data for Name: service_package; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.service_package (id, discount_pct, preset_id, service_id) FROM stdin;
15	20.00	2	16
16	\N	1	6
17	\N	15	6
\.


--
-- Data for Name: ship_vias; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ship_vias (id, shipvia_cd, shipvia_desc, vendor_id, api_base_url, auth_url, api_version, sandbox_url, logo_url, is_active, documentation_url, connection_guide, created_at, updated_at) FROM stdin;
1	118	UPS - WorldEase Saver	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
2	153	UPS - Expedited (AU)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
3	154	UPS - Saver (AU)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
4	155	UPS - Expedited (SA)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
5	156	UPS - Saver (SA)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
6	174	UPS - Expedited (HMJ)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
7	175	UPS - Saver (HMJ)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
8	184	UPS - Saver (EU)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
9	187	UPS - Saver (UK)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
10	232	UPS - Saver (CAD)	UPS	\N	\N	\N	\N	\N	t	\N	\N	\N	\N
150	F77	FedEx Ground	FEDEX	https://apis.fedex.com	/oauth/token	v1	https://apis-sandbox.fedex.com	https://www.fedex.com/images/fedex-logo.png	t	https://developer.fedex.com/api/en-us/home.html	\N	\N	\N
149	P80	UPS Ground	UPS	https://onlinetools.ups.com	/oauth/token	v1	https://wwwcie.ups.com	https://www.ups.com/assets/resources/images/logo.svg	t	\N	\N	\N	\N
151	L01	USPS	USPS	https://api.stamps.com	/auth/v1/token	v1	https://api.stamps.com	https://www.stamps.com/images/logo.png	t	https://www.stamps.com/api/docs	Connect via Stamps.com API using Client ID and Secret	\N	\N
\.


--
-- Data for Name: shipping_service; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shipping_service (id, carrier, created_at, enabled, name, scope, service_code, sort_order, updated_at, origin_country, source, synced_at, max_weight_lb, max_length_in, max_length_girth_in, surcharge_length_girth_in) FROM stdin;
17	USPS	2026-07-18 11:32:25.35532	t	USPS Ground Advantage	DOMESTIC	GROUND_ADVANTAGE	0	2026-07-20 19:38:54.978013	US	CARRIER_SYNC	2026-07-20 19:38:54.962996	70	\N	130	\N
18	USPS	2026-07-18 11:32:25.360717	t	USPS Priority Mail	DOMESTIC	PRIORITY	1	2026-07-20 19:38:54.996984	US	CARRIER_SYNC	2026-07-20 19:38:54.962996	70	\N	108	\N
19	USPS	2026-07-18 11:32:25.377925	t	USPS Priority Mail Express	DOMESTIC	PRIORITY_EXPRESS	2	2026-07-20 19:38:55.001781	US	CARRIER_SYNC	2026-07-20 19:38:54.962996	70	\N	108	\N
20	USPS	2026-07-18 11:32:25.39008	t	USPS First-Class Package Intl	INTERNATIONAL	FIRST_CLASS_INTL	3	2026-07-20 19:38:55.022568	US	CARRIER_SYNC	2026-07-20 19:38:54.962996	70	\N	130	\N
21	USPS	2026-07-18 11:32:25.394726	t	USPS Priority Mail Intl	INTERNATIONAL	PRIORITY_INTL	4	2026-07-20 19:38:55.026271	US	CARRIER_SYNC	2026-07-20 19:38:54.962996	70	\N	108	\N
32	FEDEX	2026-07-20 16:05:03.945607	t	FedEx Europe First Intl Priority	INTERNATIONAL	EUROPE_FIRST_INTERNATIONAL_PRIORITY	1	2026-07-20 16:05:03.945621	DE	CARRIER_SYNC	2026-07-20 16:05:03.937147	150	119	165	130
33	FEDEX	2026-07-20 16:05:03.948949	t	FedEx International Priority	INTERNATIONAL	INTERNATIONAL_PRIORITY	2	2026-07-20 16:05:03.948957	DE	CARRIER_SYNC	2026-07-20 16:05:03.937147	150	119	165	130
31	FEDEX	2026-07-20 16:05:03.94047	t	FedEx Priority	DOMESTIC	FEDEX_PRIORITY	0	2026-07-20 16:05:03.940482	DE	CARRIER_SYNC	2026-07-20 16:05:03.937147	150	119	165	130
34	FEDEX	2026-07-20 16:05:03.952204	t	FedEx International Economy	INTERNATIONAL	INTERNATIONAL_ECONOMY	3	2026-07-20 16:05:03.952218	DE	CARRIER_SYNC	2026-07-20 16:05:03.937147	150	119	165	130
35	FEDEX	2026-07-20 16:05:03.956117	t	FedEx International First	INTERNATIONAL	INTERNATIONAL_FIRST	4	2026-07-20 16:05:03.95613	DE	CARRIER_SYNC	2026-07-20 16:05:03.937147	150	119	165	130
28	FEDEX	2026-07-20 15:44:16.547418	t	FedEx International Priority	INTERNATIONAL	INTERNATIONAL_PRIORITY	0	2026-07-20 15:44:16.547433	IN	CARRIER_SYNC	2026-07-20 15:44:16.544562	150	119	165	130
29	FEDEX	2026-07-20 15:44:16.553975	t	FedEx International Economy	INTERNATIONAL	INTERNATIONAL_ECONOMY	1	2026-07-20 15:44:16.553984	IN	CARRIER_SYNC	2026-07-20 15:44:16.544562	150	119	165	130
30	FEDEX	2026-07-20 15:44:16.574697	t	FedEx International First	INTERNATIONAL	INTERNATIONAL_FIRST	2	2026-07-20 15:44:16.574707	IN	CARRIER_SYNC	2026-07-20 15:44:16.544562	150	119	165	130
23	UPS	2026-07-20 15:44:16.404226	t	UPS Standard	DOMESTIC	11	0	2026-07-20 15:44:43.386346	DE	CARRIER_SYNC	2026-07-20 15:44:43.380314	150	108	165	130
24	UPS	2026-07-20 15:44:16.435898	t	UPS Express Saver	INTERNATIONAL	65	1	2026-07-20 15:44:43.392374	DE	CARRIER_SYNC	2026-07-20 15:44:43.380314	150	108	165	130
25	UPS	2026-07-20 15:44:16.439984	t	UPS Express	INTERNATIONAL	07	2	2026-07-20 15:44:43.397469	DE	CARRIER_SYNC	2026-07-20 15:44:43.380314	150	108	165	130
26	UPS	2026-07-20 15:44:16.443486	t	UPS Express Plus	INTERNATIONAL	54	3	2026-07-20 15:44:43.405394	DE	CARRIER_SYNC	2026-07-20 15:44:43.380314	150	108	165	130
27	UPS	2026-07-20 15:44:16.447755	t	UPS Expedited	INTERNATIONAL	08	4	2026-07-20 15:44:43.427242	DE	CARRIER_SYNC	2026-07-20 15:44:43.380314	150	108	165	130
41	UPS	2026-07-20 17:02:05.523289	t	UPS Worldwide Express	INTERNATIONAL	07	2	2026-07-20 17:02:05.523298	JP	CARRIER_SYNC	2026-07-20 17:02:05.466716	150	108	165	130
42	UPS	2026-07-20 17:02:05.527198	t	UPS Worldwide Express Plus	INTERNATIONAL	54	3	2026-07-20 17:02:05.527206	JP	CARRIER_SYNC	2026-07-20 17:02:05.466716	150	108	165	130
39	UPS	2026-07-20 17:02:05.485592	t	UPS Worldwide Saver	INTERNATIONAL	65	0	2026-07-20 17:02:05.485613	JP	CARRIER_SYNC	2026-07-20 17:02:05.466716	150	108	165	130
40	UPS	2026-07-20 17:02:05.519273	t	UPS Worldwide Expedited	INTERNATIONAL	08	1	2026-07-20 17:02:05.519283	JP	CARRIER_SYNC	2026-07-20 17:02:05.466716	150	108	165	130
48	FEDEX	2026-07-20 19:58:08.633945	t	FedEx Priority	DOMESTIC	FEDEX_PRIORITY	0	2026-07-20 19:58:08.633957	ES	CARRIER_SYNC	2026-07-20 19:58:08.632113	150	119	165	130
1	UPS	2026-07-18 11:32:25.073478	t	UPS Ground	DOMESTIC	03	0	2026-07-20 18:24:42.76715	US	CARRIER_SYNC	2026-07-20 18:24:42.756037	150	108	165	130
2	UPS	2026-07-18 11:32:25.131186	t	UPS 3 Day Select	DOMESTIC	12	1	2026-07-20 18:24:42.779293	US	CARRIER_SYNC	2026-07-20 18:24:42.756037	150	108	165	130
3	UPS	2026-07-18 11:32:25.140278	t	UPS 2nd Day Air	DOMESTIC	02	2	2026-07-20 18:24:42.785198	US	CARRIER_SYNC	2026-07-20 18:24:42.756037	150	108	165	130
4	UPS	2026-07-18 11:32:25.148838	t	UPS Next Day Air	DOMESTIC	01	3	2026-07-20 18:24:42.790857	US	CARRIER_SYNC	2026-07-20 18:24:42.756037	150	108	165	130
6	UPS	2026-07-18 11:32:25.182229	t	UPS Worldwide Saver	INTERNATIONAL	65	4	2026-07-20 18:24:42.796678	US	CARRIER_SYNC	2026-07-20 18:24:42.756037	150	108	165	130
7	UPS	2026-07-18 11:32:25.226997	t	UPS Worldwide Expedited	INTERNATIONAL	08	5	2026-07-20 18:24:42.816628	US	CARRIER_SYNC	2026-07-20 18:24:42.756037	150	108	165	130
8	UPS	2026-07-18 11:32:25.277586	t	UPS Worldwide Express	INTERNATIONAL	07	6	2026-07-20 18:24:42.821668	US	CARRIER_SYNC	2026-07-20 18:24:42.756037	150	108	165	130
22	USPS	2026-07-18 11:32:25.403549	t	USPS Priority Mail Express Intl	INTERNATIONAL	EXPRESS_INTL	5	2026-07-20 19:38:55.033128	US	CARRIER_SYNC	2026-07-20 19:38:54.962996	70	\N	130	\N
9	FEDEX	2026-07-18 11:32:25.287609	t	FedEx Ground	DOMESTIC	FEDEX_GROUND	0	2026-07-20 19:44:10.621631	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	108	165	130
10	FEDEX	2026-07-18 11:32:25.295185	t	FedEx Home Delivery	DOMESTIC	GROUND_HOME_DELIVERY	1	2026-07-20 19:44:10.625316	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	108	165	130
11	FEDEX	2026-07-18 11:32:25.301625	t	FedEx Express Saver	DOMESTIC	FEDEX_EXPRESS_SAVER	2	2026-07-20 19:44:10.629524	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	119	165	130
12	FEDEX	2026-07-18 11:32:25.311485	t	FedEx 2Day	DOMESTIC	FEDEX_2_DAY	3	2026-07-20 19:44:10.634526	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	119	165	130
13	FEDEX	2026-07-18 11:32:25.324414	t	FedEx Standard Overnight	DOMESTIC	STANDARD_OVERNIGHT	4	2026-07-20 19:44:10.639759	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	119	165	130
14	FEDEX	2026-07-18 11:32:25.328684	t	FedEx Priority Overnight	DOMESTIC	PRIORITY_OVERNIGHT	5	2026-07-20 19:44:10.644479	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	119	165	130
15	FEDEX	2026-07-18 11:32:25.3346	t	FedEx International Economy	INTERNATIONAL	INTERNATIONAL_ECONOMY	6	2026-07-20 19:44:10.647641	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	119	165	130
16	FEDEX	2026-07-18 11:32:25.346444	t	FedEx International Priority	INTERNATIONAL	INTERNATIONAL_PRIORITY	7	2026-07-20 19:44:10.650022	US	CARRIER_SYNC	2026-07-20 19:44:10.619441	150	119	165	130
43	UPS	2026-07-20 19:58:07.4691	t	UPS Standard	DOMESTIC	11	0	2026-07-20 19:58:07.469137	ES	CARRIER_SYNC	2026-07-20 19:58:07.455781	150	108	165	130
44	UPS	2026-07-20 19:58:07.477323	t	UPS Express Saver	INTERNATIONAL	65	1	2026-07-20 19:58:07.477333	ES	CARRIER_SYNC	2026-07-20 19:58:07.455781	150	108	165	130
45	UPS	2026-07-20 19:58:07.481411	t	UPS Express	INTERNATIONAL	07	2	2026-07-20 19:58:07.481422	ES	CARRIER_SYNC	2026-07-20 19:58:07.455781	150	108	165	130
46	UPS	2026-07-20 19:58:07.48726	t	UPS Express Plus	INTERNATIONAL	54	3	2026-07-20 19:58:07.487278	ES	CARRIER_SYNC	2026-07-20 19:58:07.455781	150	108	165	130
47	UPS	2026-07-20 19:58:07.491574	t	UPS Expedited	INTERNATIONAL	08	4	2026-07-20 19:58:07.491583	ES	CARRIER_SYNC	2026-07-20 19:58:07.455781	150	108	165	130
49	FEDEX	2026-07-20 19:58:08.641604	t	FedEx Europe First Intl Priority	INTERNATIONAL	EUROPE_FIRST_INTERNATIONAL_PRIORITY	1	2026-07-20 19:58:08.641637	ES	CARRIER_SYNC	2026-07-20 19:58:08.632113	150	119	165	130
50	FEDEX	2026-07-20 19:58:08.647792	t	FedEx International Priority	INTERNATIONAL	INTERNATIONAL_PRIORITY	2	2026-07-20 19:58:08.647806	ES	CARRIER_SYNC	2026-07-20 19:58:08.632113	150	119	165	130
51	FEDEX	2026-07-20 19:58:08.669073	t	FedEx International Economy	INTERNATIONAL	INTERNATIONAL_ECONOMY	3	2026-07-20 19:58:08.669085	ES	CARRIER_SYNC	2026-07-20 19:58:08.632113	150	119	165	130
52	FEDEX	2026-07-20 19:58:08.674025	t	FedEx International First	INTERNATIONAL	INTERNATIONAL_FIRST	4	2026-07-20 19:58:08.67404	ES	CARRIER_SYNC	2026-07-20 19:58:08.632113	150	119	165	130
36	FEDEX	2026-07-20 16:05:38.652735	t	FedEx International Priority	INTERNATIONAL	INTERNATIONAL_PRIORITY	0	2026-07-20 20:42:55.153751	JP	CARRIER_SYNC	2026-07-20 20:42:55.140073	150	119	165	130
37	FEDEX	2026-07-20 16:05:38.674419	t	FedEx International Economy	INTERNATIONAL	INTERNATIONAL_ECONOMY	1	2026-07-20 20:42:55.190333	JP	CARRIER_SYNC	2026-07-20 20:42:55.140073	150	119	165	130
38	FEDEX	2026-07-20 16:05:38.679108	t	FedEx International First	INTERNATIONAL	INTERNATIONAL_FIRST	2	2026-07-20 20:42:55.196609	JP	CARRIER_SYNC	2026-07-20 20:42:55.140073	150	119	165	130
\.


--
-- Data for Name: shipvia_service_mapping; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.shipvia_service_mapping (id, created_at, service_id, shipvia_cd, updated_at, client_code, dest_type, dest_value) FROM stdin;
1	2026-07-18 11:32:25.564633	1	P80	2026-07-18 11:32:25.564717	\N	\N	\N
3	2026-07-18 11:32:25.658452	18	L01	2026-07-18 11:32:25.658493	\N	\N	\N
2	2026-07-18 11:32:25.640029	9	F77	2026-07-20 16:34:15.778672	\N	ANY	\N
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, username, email, password, full_name, role, preferred_carrier, carrier_client_id, carrier_client_secret, carrier_account_number, carrier_access_token, carrier_token_expires_at, carrier_connected, carrier_connected_at, carrier_environment, created_at, updated_at) FROM stdin;
2	Malaya2000	dalabehera147@gmail.com	$2a$10$yTHQvYWmSASzq5125q8k6eD1q44VIV0MvYokicKxj/ouVnJaS3WbC	malaya ranjan dalabehera	USER	\N	\N	\N	\N	\N	\N	f	\N	SANDBOX	2026-07-09 17:06:34.233907	2026-07-09 17:06:34.234096
1	MALAYARANJAN2000	ranjanmalayatwo000@gmail.com	$2a$10$0wW0krINA3bn0yrTZBjGjuMPVMlbYQ87EkevWnwmqgAkKoJc3Mdoa	malaya ranjan dalabehera	USER	\N	\N	\N	\N	\N	\N	f	\N	SANDBOX	2026-07-09 08:58:47.425899	2026-07-09 15:50:25.176677
3	admin	admin@multiship.com	$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG	Admin User	ADMIN	\N	\N	\N	\N	\N	\N	f	\N	SANDBOX	2026-07-10 09:21:58.169813	2026-07-10 09:21:58.169813
4	shipping_user	shipping@multiship.com	$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG	Shipping User	USER	\N	\N	\N	\N	\N	\N	f	\N	SANDBOX	2026-07-10 09:21:58.169813	2026-07-10 09:21:58.169813
6	shipteam	shipteam@example.com	$2a$10$tpW6BvqtkQYw71/G/qj7JOcMf0h9.LV0e.hvBy1bgLn39Bu32D2z2	Shipping Team	USER	\N	\N	\N	\N	\N	\N	f	\N	SANDBOX	2026-07-10 16:13:59.235899	2026-07-10 16:13:59.235947
7	arhdev	arhdev@example.com	$2a$10$y649oQIJ.orHESmM3WKBiOKyFjA17dyjVKEP69Wa0xHnLuGddtNiq	ARH Development	TENANT	\N	\N	\N	\N	\N	\N	f	\N	SANDBOX	2026-07-10 16:13:59.34047	2026-07-10 16:13:59.340481
5	e2etester	e2etester@example.com	$2a$10$1MXvRpR2iepcYXeMT5Wqc.oRxoHldT9ByFWPDyC6MSZls7d1qZZle	E2E Tester	ADMIN	UPS	746W05	N9zxIJT4kkdkfWj4WFOh5zpXWDzOErW3GwNIounGNgOdgXqy	A0lmFeeYjcJlvRpIOUAesEubMUWfCMVVFhAZN1PoAGNWLaBj2EjddYYoLCtUYAkI	ups-local-02dd15cffeee3c36	2026-07-14 10:26:13.603015	t	2026-07-14 14:56:13.603031	SANDBOX	2026-07-10 15:31:43.157255	2026-07-10 15:31:43.157284
\.


--
-- Name: carrier_account_ref_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.carrier_account_ref_id_seq', 21, true);


--
-- Name: carrier_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.carrier_config_id_seq', 28, true);


--
-- Name: client_customs_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.client_customs_profile_id_seq', 21, true);


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clients_id_seq', 13, true);


--
-- Name: customs_profile_country_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.customs_profile_country_id_seq', 28, true);


--
-- Name: order_carrier_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_carrier_details_id_seq', 16, true);


--
-- Name: order_customs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_customs_id_seq', 4, true);


--
-- Name: order_customs_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_customs_item_id_seq', 6, true);


--
-- Name: order_label_tracking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_label_tracking_id_seq', 122, true);


--
-- Name: order_lines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.order_lines_id_seq', 112, true);


--
-- Name: package_preset_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.package_preset_id_seq', 41, true);


--
-- Name: service_package_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.service_package_id_seq', 17, true);


--
-- Name: shipping_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shipping_service_id_seq', 52, true);


--
-- Name: shipvia_service_mapping_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.shipvia_service_mapping_id_seq', 10, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: carrier_account_ref carrier_account_ref_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier_account_ref
    ADD CONSTRAINT carrier_account_ref_pkey PRIMARY KEY (id);


--
-- Name: carrier_config carrier_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier_config
    ADD CONSTRAINT carrier_config_pkey PRIMARY KEY (id);


--
-- Name: client_customs_profile client_customs_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_customs_profile
    ADD CONSTRAINT client_customs_profile_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: customs_profile_country customs_profile_country_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customs_profile_country
    ADD CONSTRAINT customs_profile_country_pkey PRIMARY KEY (id);


--
-- Name: label_batch label_batch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.label_batch
    ADD CONSTRAINT label_batch_pkey PRIMARY KEY (order_no);


--
-- Name: order_carrier_details order_carrier_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_carrier_details
    ADD CONSTRAINT order_carrier_details_pkey PRIMARY KEY (id);


--
-- Name: order_customs_item order_customs_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_customs_item
    ADD CONSTRAINT order_customs_item_pkey PRIMARY KEY (id);


--
-- Name: order_customs order_customs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_customs
    ADD CONSTRAINT order_customs_pkey PRIMARY KEY (id);


--
-- Name: order_label_tracking order_label_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_label_tracking
    ADD CONSTRAINT order_label_tracking_pkey PRIMARY KEY (id);


--
-- Name: order_lines order_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_pkey PRIMARY KEY (id);


--
-- Name: package_preset package_preset_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.package_preset
    ADD CONSTRAINT package_preset_pkey PRIMARY KEY (id);


--
-- Name: service_package service_package_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_package
    ADD CONSTRAINT service_package_pkey PRIMARY KEY (id);


--
-- Name: ship_vias ship_vias_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ship_vias
    ADD CONSTRAINT ship_vias_pkey PRIMARY KEY (id);


--
-- Name: shipping_service shipping_service_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_service
    ADD CONSTRAINT shipping_service_pkey PRIMARY KEY (id);


--
-- Name: shipvia_service_mapping shipvia_service_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipvia_service_mapping
    ADD CONSTRAINT shipvia_service_mapping_pkey PRIMARY KEY (id);


--
-- Name: clients uk59ust0ah2ojukr079kddthcrm; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uk59ust0ah2ojukr079kddthcrm UNIQUE (client_code);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: order_customs uk7p5ddu2ol21sp0xavvfnh8yk7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_customs
    ADD CONSTRAINT uk7p5ddu2ol21sp0xavvfnh8yk7 UNIQUE (order_no);


--
-- Name: carrier_account_ref uk_account_ref_number_carrier; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier_account_ref
    ADD CONSTRAINT uk_account_ref_number_carrier UNIQUE (account_number, carrier_code);


--
-- Name: order_carrier_details uk_order_carrier_details_order; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_carrier_details
    ADD CONSTRAINT uk_order_carrier_details_order UNIQUE (order_no);


--
-- Name: order_label_tracking uk_order_tracking; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_label_tracking
    ADD CONSTRAINT uk_order_tracking UNIQUE (order_no, order_suffix);


--
-- Name: carrier_config uk_tenant_carrier_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier_config
    ADD CONSTRAINT uk_tenant_carrier_account UNIQUE (tenant_id, carrier_code, account_code);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: customs_profile_country uq_customs_country_client; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customs_profile_country
    ADD CONSTRAINT uq_customs_country_client UNIQUE (client_code, country);


--
-- Name: service_package uq_service_package; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.service_package
    ADD CONSTRAINT uq_service_package UNIQUE (service_id, preset_id);


--
-- Name: shipping_service uq_shipping_service_lane; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipping_service
    ADD CONSTRAINT uq_shipping_service_lane UNIQUE (carrier, service_code, origin_country);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_carrier_config_carrier_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrier_config_carrier_code ON public.carrier_config USING btree (carrier_code);


--
-- Name: idx_carrier_config_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrier_config_tenant ON public.carrier_config USING btree (tenant_id);


--
-- Name: idx_carrier_config_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_carrier_config_user_id ON public.carrier_config USING btree (user_id);


--
-- Name: idx_customs_country_profile; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customs_country_profile ON public.customs_profile_country USING btree (profile_id);


--
-- Name: idx_customs_profile_client; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_customs_profile_client ON public.client_customs_profile USING btree (client_code);


--
-- Name: idx_order_lines_order_no; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_lines_order_no ON public.order_lines USING btree (order_no);


--
-- Name: idx_order_lines_tenant_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_lines_tenant_id ON public.order_lines USING btree (tenant_id);


--
-- Name: idx_shipvia_rule_code; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shipvia_rule_code ON public.shipvia_service_mapping USING btree (shipvia_cd);


--
-- Name: uk_carrier_config_user_carrier_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_carrier_config_user_carrier_tenant ON public.carrier_config USING btree (user_id, carrier_code, COALESCE(tenant_id, '__OPERATOR__'::character varying));


--
-- Name: uq_preset_carrier_lane; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_preset_carrier_lane ON public.package_preset USING btree (carrier, carrier_package_code, origin_country) WHERE ((kind)::text = 'CARRIER'::text);


--
-- Name: uq_preset_custom_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_preset_custom_name ON public.package_preset USING btree (lower((name)::text)) WHERE ((kind)::text = 'CUSTOM'::text);


--
-- Name: carrier_config carrier_config_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier_config
    ADD CONSTRAINT carrier_config_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: customs_profile_country customs_profile_country_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.customs_profile_country
    ADD CONSTRAINT customs_profile_country_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.client_customs_profile(id) ON DELETE CASCADE;


--
-- Name: carrier_config fk5sh6jbljbvs3atd2lev2jfvcg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carrier_config
    ADD CONSTRAINT fk5sh6jbljbvs3atd2lev2jfvcg FOREIGN KEY (ship_via_id) REFERENCES public.ship_vias(id);


--
-- Name: order_customs_item fkb4eiry1al70ex5dx9k3eavv1e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_customs_item
    ADD CONSTRAINT fkb4eiry1al70ex5dx9k3eavv1e FOREIGN KEY (order_customs_id) REFERENCES public.order_customs(id);


--
-- Name: order_lines order_lines_order_no_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_lines
    ADD CONSTRAINT order_lines_order_no_fkey FOREIGN KEY (order_no) REFERENCES public.label_batch(order_no) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict OgBsXYB4JDo0CXLyVmgLz9WV2uIIqYmaurKAwzb6BkmmxOWa0bWzWtZdhCdyGnR

