import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { notify } from '../../utils/notify'
import { FiFileText, FiRefreshCw, FiTag, FiTruck } from 'react-icons/fi'
import { orderService, type Order } from '../../api/orderService'
import { formatCarrierName } from '../../utils/carrierUtils'
import OrderDetailsModal from '../modals/OrderDetailsModal'
import TrackingTimelineModal from '../tracking/TrackingTimelineModal'
import OrdersTable from './OrdersTable'
import PageSectionHeader from './PageSectionHeader'
import TablePagination from './TablePagination'
import { statusTabs, type OrderStatusFilter, formatNumber } from './orderUtils'

interface TenantOrdersViewProps {
  tenantId: string
}

/**
 * Read-only order view for TENANT users, scoped to their own orders. All
 * filtering, searching, and pagination happen server-side via the unified
 * list endpoint (GET /orders?tenantId=...).
 */
export default function TenantOrdersView({ tenantId }: TenantOrdersViewProps) {
  const navigate = useNavigate()
  const [orders, setOrders] = useState<Order[]>([])
  const [loading, setLoading] = useState(true)
  const [statusFilter, setStatusFilter] = useState<OrderStatusFilter>('ALL')
  const [search, setSearch] = useState('')
  const [debouncedSearch, setDebouncedSearch] = useState('')
  const [page, setPage] = useState(0)
  const [pageSize, setPageSize] = useState(10)
  const [totalElements, setTotalElements] = useState(0)
  const [totalPages, setTotalPages] = useState(1)
  const [detailsOrderNo, setDetailsOrderNo] = useState<number | null>(null)
  const [trackingOrderNo, setTrackingOrderNo] = useState<number | null>(null)
  const [reloadToken, setReloadToken] = useState(0)

  // Debounce the search box so we don't hit the server per keystroke.
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(search)
      setPage(0)
    }, 350)
    return () => clearTimeout(timer)
  }, [search])

  useEffect(() => {
    let cancelled = false

    const load = async () => {
      setLoading(true)
      try {
        const response = await orderService.listOrders({
          tenantId,
          status: statusFilter !== 'ALL' ? statusFilter : undefined,
          search: debouncedSearch || undefined,
          page,
          size: pageSize,
          sortBy: 'orderNo',
          sortDirection: 'ASC',
          includeResolution: true,
        })

        if (cancelled) return
        setOrders(response.data?.content ?? [])
        setTotalElements(response.data?.totalElements ?? 0)
        setTotalPages(Math.max(response.data?.totalPages ?? 1, 1))
      } catch (error) {
        if (cancelled) return
        notify.error(error instanceof Error ? error.message : 'Failed to load your orders.')
        setOrders([])
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    void load()
    return () => {
      cancelled = true
    }
  }, [tenantId, statusFilter, debouncedSearch, page, pageSize, reloadToken])

  return (
    <div className="space-y-4">
      <PageSectionHeader
        eyebrow="Your Orders"
        title="Your orders"
        description={`Shipment activity for ${tenantId} — labels are generated by the shipping team.`}
        actions={
          <button
            type="button"
            onClick={() => setReloadToken((token) => token + 1)}
            className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 py-1.5 text-[13px] font-semibold text-slate-700 transition hover:bg-slate-50"
          >
            <FiRefreshCw className="h-3.5 w-3.5" />
            Refresh
          </button>
        }
      />

      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <div className="flex flex-col gap-2.5 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex flex-wrap gap-1.5">
            {statusTabs.map((status) => (
              <button
                key={status}
                type="button"
                onClick={() => {
                  setStatusFilter(status)
                  setPage(0)
                }}
                className={`inline-flex items-center gap-1.5 rounded-xl px-2.5 py-1.5 text-[11px] font-semibold transition sm:px-3 sm:text-xs ${
                  statusFilter === status
                    ? 'bg-[#1f150c] text-white'
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200 hover:text-slate-950'
                }`}
              >
                {status}
              </button>
            ))}
          </div>

          <label className="block min-w-[240px] flex-1 lg:max-w-sm">
            <span className="sr-only">Search your orders</span>
            <input
              type="search"
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Search by order #, destination, or tracking"
              className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-3 py-2 text-[13px] text-slate-950 outline-none transition focus:border-sky-600 focus:ring-4 focus:ring-sky-100"
            />
          </label>
        </div>

        <p className="mt-2.5 text-[11px] text-slate-500">
          {formatNumber(totalElements)} order{totalElements === 1 ? '' : 's'} match the current filters
        </p>
      </section>

      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <OrdersTable
          orders={orders}
          loading={loading}
          mode="tracking"
          compact
          emptyText={
            loading
              ? 'Loading your orders...'
              : `No orders found for ${tenantId} with the current filters.`
          }
          renderAccount={(order: Order) => {
            const resolution = order.accountResolution

            return resolution?.accountNumber ? (
              <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-semibold text-slate-700">
                {formatCarrierName(resolution.carrierCode || '')} • {resolution.accountNumber}
              </span>
            ) : (
              <span className="text-slate-400">—</span>
            )
          }}
          renderAction={(order: Order) => (
            <div className="inline-flex items-center gap-2">
              {order.labelDetails.trackingNumber ? (
                <button
                  type="button"
                  onClick={() => navigate(`/label/${order.orderDetails.orderNo}`)}
                  className="inline-flex items-center gap-1.5 rounded-xl bg-[#1f150c] px-3 py-1.5 text-[11px] font-semibold text-white transition hover:bg-[#412d15]"
                >
                  <FiTag className="h-3 w-3" />
                  Label
                </button>
              ) : null}
              {order.labelDetails.trackingNumber ? (
                <button
                  type="button"
                  onClick={() => setTrackingOrderNo(order.orderDetails.orderNo)}
                  title={`Live tracking for ${order.labelDetails.trackingNumber}`}
                  className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 py-1.5 text-[11px] font-semibold text-slate-700 transition hover:bg-slate-50"
                >
                  <FiTruck className="h-3 w-3" />
                  Track
                </button>
              ) : null}
              <button
                type="button"
                onClick={() => setDetailsOrderNo(order.orderDetails.orderNo)}
                className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 py-1.5 text-[11px] font-semibold text-slate-700 transition hover:bg-slate-50"
              >
                <FiFileText className="h-3 w-3" />
                Details
              </button>
            </div>
          )}
        />

        {totalElements > 0 ? (
          <TablePagination
            page={page + 1}
            pageSize={pageSize}
            totalPages={totalPages}
            compact
            onPageChange={(next) => setPage(next - 1)}
            onPageSizeChange={(size) => {
              setPageSize(size)
              setPage(0)
            }}
          />
        ) : null}
      </section>

      {detailsOrderNo !== null ? (
        <OrderDetailsModal orderNo={detailsOrderNo} onClose={() => setDetailsOrderNo(null)} />
      ) : null}

      {trackingOrderNo !== null ? (
        <TrackingTimelineModal orderNo={trackingOrderNo} onClose={() => setTrackingOrderNo(null)} />
      ) : null}
    </div>
  )
}
